<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back' => '',
    'Cancel' => '',
    'Clients' => '',
    'Create' => '',
    'Create Client' => '',
    'Edit' => '',
    'General Overview' => '',
    'General info' => '',
    'If photo not uploaded, default avatar will be used' => '',
    'If you forgot your password you can' => '',
    'Login' => '',
    'Logout' => '',
    'Manage' => '',
    'Password' => '',
    'Personal Info' => '',
    'Picture' => '',
    'Profile Picture' => '',
    'Protip: ' => '',
    'Register' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'reset it' => '',
    'Are you sure you want to delete this item?' => '@@@@',
    'If you think this is a mistake, please contact Support.' => '@@@@',
    'Please fill the next fields' => '@@@@',
    'Signup' => '@@@@',
    'User\'s list' => '@@@@',
    'Delete' => '@@@@',
];
