<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accessory Of' => '',
    'Acquisition Price' => '',
    'Add' => '',
    'Back' => '',
    'Brand' => '',
    'Brand ID' => '',
    'Brands' => '',
    'Cancel' => '',
    'Categories' => '',
    'Category' => '',
    'Category ID' => '',
    'Clients' => '',
    'Create' => '',
    'Create Brand' => '',
    'Create Category' => '',
    'Create Client' => '',
    'Create Item' => '',
    'Create Item Description' => '',
    'Created At' => '',
    'Created By' => '',
    'Description' => '',
    'Edit' => '',
    'Existence' => '',
    'General Overview' => '',
    'General info' => '',
    'ID' => '',
    'If photo not uploaded, default avatar will be used' => '',
    'If you forgot your password you can' => '',
    'Item Descriptions' => '',
    'Item ID' => '',
    'Items' => '',
    'Login' => '',
    'Logout' => '',
    'Manage' => '',
    'Model' => '',
    'Name' => '',
    'Password' => '',
    'Personal Info' => '',
    'Picture' => '',
    'Profile Picture' => '',
    'Protip: ' => '',
    'Register' => '',
    'Rent Price' => '',
    'Reset' => '',
    'Sale' => '',
    'Save' => '',
    'Search' => '',
    'Sell Price' => '',
    'Serial Number' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Updated By' => '',
    'reset it' => '',
    'If you think this is a mistake, please contact Support.' => '@@@@',
    'Please fill the next fields' => '@@@@',
    'Signup' => '@@@@',
    'User\'s list' => '@@@@',
    'Are you sure you want to delete this item?' => '@@@@',
    'Delete' => '@@@@',
];
