<?php
/**
 * Created by IntelliJ IDEA.
 * User: zero_
 * Date: 02/10/2016
 * Time: 11:15 PM
 */

namespace common\custom\widgets\grid;


use yii\base\Model;
use yii\helpers\Html;

class DataColumn extends \yii\grid\DataColumn
{
    public function renderFilterCell()
    {
        return Html::tag('i', 'filter_list', ['class' => 'mdi prefix']) . parent::renderFilterCell(); // TODO: Change the autogenerated stub
    }


    protected function renderFilterCellContent()
    {
        if (is_string($this->filter)) {
            return $this->filter;
        }

        $model = $this->grid->filterModel;

        if ($this->filter !== false && $model instanceof Model && $this->attribute !== null && $model->isAttributeActive($this->attribute)) {
            if ($model->hasErrors($this->attribute)) {
                Html::addCssClass($this->filterOptions, 'has-error');
                $error = ' ' . Html::error($model, $this->attribute, $this->grid->filterErrorOptions);
            } else {
                $error = '';
            }
            if (is_array($this->filter)) {
                $options = array_merge(['prompt' => ''], $this->filterInputOptions);
                return Html::activeDropDownList($model, $this->attribute, $this->filter, $options) . $error;
            } else {
                return $this->renderActiveInput($model, $error);
            }
        } else {
            return parent::renderFilterCellContent();
        }
    }

    /**
     * @param $model Model
     * @param $error
     * @return string
     */
    protected function renderActiveInput($model, $error)
    {
        if (!isset($this->filterInputOptions['type'])) { // Add filter icon to field
            return e()Html::activeTextInput(
                $model,
                $this->attribute,
                $this->filterInputOptions
            ) . $error;
        }
    }

}