// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    var d, err, error, loadingOverlay, timeout;
    d = $(document);
    loadingOverlay = $('#loading');
    timeout = 250;
    $('.button-collapse').sideNav();
    $('.modal-trigger').leanModal();
    $('.scrollspy').scrollSpy();
    $('.select').material_select();
    $('.dropdown-button').dropdown();
    Materialize.updateTextFields();
    try {
      document.getElementById('main').scrollIntoView({
        block: 'end',
        behavior: 'smooth'
      });
    } catch (error) {
      err = error;
    }
    $('.collapsible').collapsible({
      accordion: false
    });
    d.on('pjax:beforeSend', function() {
      loadingOverlay.show(timeout);
    });
    d.on('pjax:error', function() {
      Materialize.toast('Ocurrió un error');
    });
    d.on('pjax:end', function() {
      $('.tooltipped').tooltip();
      loadingOverlay.hide(timeout);
    });
    $('.datepicker').pickadate();
    return true;
  });

}).call(this);

//# sourceMappingURL=main.js.map
