// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    var d, err, error, hamburger_cross, isClosed, loadingOverlay, overlay, timeout, trigger;
    d = $(document);
    loadingOverlay = $('#loading');
    timeout = 250;
    $('.button-collapse').sideNav();
    $('.modal-trigger').leanModal();
    $('.scrollspy').scrollSpy();
    $('.select').material_select();
    $('.dropdown-button').dropdown();
    try {
      document.getElementById('main').scrollIntoView({
        block: 'end',
        behavior: 'smooth'
      });
    } catch (error) {
      err = error;
    }
    $('.collapsible').collapsible({
      accordion: false
    });
    d.on('pjax:beforeSend', function() {
      loadingOverlay.show(timeout);
    });
    d.on('pjax:error', function() {
      Materialize.toast('Ocurrió un error');
    });
    d.on('pjax:end', function() {
      $('.tooltipped').tooltip();
      loadingOverlay.hide(timeout);
    });
    $('.datepicker').pickadate();
    trigger = $('.hamburger');
    overlay = $('.overlay');
    isClosed = false;
    hamburger_cross = function() {
      if (isClosed === true) {
        overlay.hide();
        trigger.removeClass('is-open');
        trigger.addClass('is-closed');
        isClosed = false;
      } else {
        overlay.show();
        trigger.removeClass('is-closed');
        trigger.addClass('is-open');
        isClosed = true;
      }
    };
    trigger.click(function() {
      hamburger_cross();
    });
    $('[data-toggle="offcanvas"]').click(function() {
      $('#wrapper').toggleClass('toggled');
    });
    return true;
  });

}).call(this);

//# sourceMappingURL=main.js.map
