<?php

use backend\models\Role;
use yii\base\Model;

class RoleSearch extends Role
{
    public function rules()
    {
        return [
            [['name', 'description'], 'safe']
        ];
    }

    public function scenarios()
    {
        return Model::scenarios(); // TODO: Change the autogenerated stub
    }


}