<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actual list of roles' => '',
    'Add children roles' => '',
    'Add roles' => '',
    'Admin Panel' => '',
    'An error has ocurred, maybe a typo?' => '',
    'Assign only the necessary role for this user' => '',
    'Cancel' => '',
    'Children' => '',
    'Children Roles' => '',
    'Create' => '',
    'Create User' => '',
    'Created At' => '',
    'Creating role' => '',
    'Data' => '',
    'Description' => '',
    'Details' => '',
    'General' => '',
    'General overview' => '',
    'Here you can add or remove existing permissions for the given role' => '',
    'Here you manage relation between roles, the actual will inherit permissions from them' => '',
    'Home' => '',
    'ID' => '',
    'If photo not uploaded, default avatar will be used' => '',
    'Login' => '',
    'Logout' => '',
    'Manage' => '',
    'Manage Permissions' => '',
    'Manage permissions' => '',
    'Manage role children' => '',
    'Name' => '',
    'Permission: {permission}' => '',
    'Permissions' => '',
    'Personal Info' => '',
    'Please login before continue' => '',
    'Profile Picture' => '',
    'Protip' => '',
    'Protip: ' => '',
    'Reset' => '',
    'Role: {role}' => '',
    'Roles' => '',
    'Roles of: {name}' => '',
    'Rule Name' => '',
    'Save' => '',
    'Search' => '',
    'Submit' => '',
    'Type' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Users' => '',
    '{name}' => '',
];
