<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Brand ID' => 'ID Marca',
    'Category' => 'ID Categoria',
    'Model' => 'Modelo',
    'If you think this is a mistake, please contact Support.' => 'Si cree que esto es un error, contacte a Soporte Técnico.',
    'Please fill the next fields' => 'Porfavor, llene los siguientes campos',
    'Signup' => 'Registrar',
    'User\'s list' => 'Lista de usuarios',
    'Accessory Of' => 'Accesorio de',
    'Acquisition Price' => 'Precio de adquisición',
    'Add' => 'Añadir',
    'Are you sure you want to delete this item?' => '¿Seguro que desea eliminar este elemento?',
    'Back' => 'Atrás',
    'Cancel' => 'Cancelar',
    'Categories' => 'Categorias',
    'Category ID' => 'ID Categoria',
    'Clients' => 'Clientes',
    'Create' => 'Crear',
    'Create Category' => 'Crear categoría',
    'Create Client' => 'Crear cliente',
    'Create Item' => 'Crear artículo',
    'Create Item Description' => 'Crear descripción de artículo',
    'Created At' => 'Creado',
    'Created By' => 'Creado por',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'Edit' => 'Editar',
    'General Overview' => 'Datos Generales',
    'General info' => 'Información general',
    'ID' => 'ID',
    'If photo not uploaded, default avatar will be used' => 'Si no se sube una fotografía, se usará el avatar por defecto',
    'If you forgot your password you can' => 'Si olvidó su contraseña, solicite',
    'Item Descriptions' => 'Descripciones de artículos',
    'Items' => 'Artículos',
    'Login' => 'Iniciar Sesión',
    'Logout' => 'Cerrar Sesión',
    'Manage' => 'Administrar',
    'Name' => 'Nombre',
    'Password' => 'Contraseña',
    'Personal Info' => 'Información personal',
    'Picture' => 'Imágen',
    'Profile Picture' => 'Foto de perfil',
    'Protip: ' => 'Tip: ',
    'Register' => 'Regístrate',
    'Rent Price' => 'Precio de renta',
    'Reset' => 'Reiniciar',
    'Sale' => 'Venta',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'Sell Price' => 'Precio de venta',
    'Serial Number' => 'Número de serie',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}: ',
    'Updated At' => 'Actualizado',
    'Updated By' => 'Actualizado por',
    'reset it' => 'reiniciarla',
];
