<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'If you think this is a mistake, please contact Support.' => 'Si cree que esto es un error, contacte a Soporte Técnico.',
    'Are you sure you want to delete this item?' => '@@¿Seguro que desea eliminar este elemento?@@',
    'Delete' => '@@Eliminar@@',
    'Cancel' => 'Cancelar',
    'Clients' => 'Clientes',
    'Create' => 'Crear',
    'Create Client' => 'Crear cliente',
    'If you forgot your password you can' => 'Si olvidó su contraseña, solicite',
    'Login' => 'Iniciar Sesión',
    'Logout' => 'Cerrar Sesión',
    'Manage' => 'Administrar',
    'Please fill the next fields' => 'Porfavor, llene los siguientes campos',
    'Register' => 'Regístrate',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Signup' => 'Registrar',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'reset it' => 'reiniciarla',
];
