<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Update: {permission}' => 'Actualizar: {permission}',
    'Access' => 'Acceso',
    'Actual list of roles' => 'Lista de roles actual',
    'Add children roles' => 'Agregar roles hijos',
    'Add roles' => 'Agregar rol',
    'Admin Panel' => 'Administración',
    'An error has ocurred, maybe a typo?' => 'Ocurrió un error',
    'Assign only the necessary role for this user' => 'Asigne sólo los roles necesarios para este usuario',
    'Binnacles' => 'Bitácoras',
    'Bitacoras' => 'Binnacles',
    'Cancel' => 'Cancelar',
    'Children' => 'Hijos',
    'Children Roles' => 'Roles hijo',
    'Create' => 'Crear',
    'Create Bitacora' => 'Crear Bitácora',
    'Create User' => 'Agregar Usuario',
    'Created At' => 'Creado',
    'Creating role' => 'Creando rol',
    'Data' => 'Datos',
    'Description' => 'Descripción',
    'Details' => 'Detalles',
    'General Overview' => 'Vista General',
    'General overview' => 'Vista General',
    'Here you can add or remove existing permissions for the given role' => 'Aquí puede agregar o remover permisos para el rol actual',
    'Here you manage relation between roles, the actual will inherit permissions from them' => 'Aquí puede administrar la relación entre roles, el actual heredará los permisos de ellos',
    'ID' => 'ID',
    'If photo not uploaded, default avatar will be used' => 'Si no se suba una foto, se usará el avatar por defecto',
    'Login' => 'Iniciar Sesión',
    'Logout' => 'Cerrar Sesión',
    'Manage Permissions' => 'Administrar permisos',
    'Manage permissions' => 'Administrar permisos',
    'Manage role children' => 'Administrar roles hijos',
    'Name' => 'Nombre',
    'Permission' => 'Permisos',
    'Permission: {permission}' => 'Permiso: {permission}',
    'Permissions' => 'Permisos',
    'Personal Info' => 'Información personal',
    'Please login before continue' => 'Porfavor, inicie sesión para continuar',
    'Profile Picture' => 'Foto de perfil',
    'Protip' => 'Tip',
    'Protip: ' => 'Tip',
    'Reset' => 'Reiniciar',
    'Role: {role}' => 'Rol',
    'Roles' => 'Roles',
    'Roles of: {name}' => 'Roles de: {name}',
    'Rule Name' => 'Nombre de la regla',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'Submit' => 'Aceptar',
    'Type' => 'Tipo',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}',
    'Updated At' => 'Actualizado',
    'Users' => 'Usuarios',
    '{name}' => '{name}',
];
